# Generated by Django 3.0.7 on 2020-07-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200714_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='websites',
            field=models.URLField(),
        ),
    ]
